#!/bin/sh
set -eu

APP_USER="${POSTGRES_APP_USER:-pt_app}"
APP_PASSWORD="${POSTGRES_APP_PASSWORD:-pt_app_password}"
APP_DB="${POSTGRES_DB:-pt_resource_hub}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_USER}') THEN
    CREATE ROLE "${APP_USER}" LOGIN PASSWORD '${APP_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  ELSE
    ALTER ROLE "${APP_USER}" WITH LOGIN PASSWORD '${APP_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "${APP_DB}" TO "${APP_USER}";
SQL
